### ISSUE TITLE
Add flag for quantization

### ISSUE THREAD

**Issue by samos123** [substratusai/vllm-docker#2]

**Comment by mxchinegod** [comment]
since we're likely to see other arg related issues in the repo, would be nice if the entrypoint contained a way to do more than [--quantization awq](https://github.com/mit-han-lab/llm-awq/blob/be78265bc08aeb2df53a0ae49dba0fe88756da4b/README.md?plain=1#L23) (like `--dtype`)

**Comment by samos123** [comment]
Agreed, thanks for the feedback! I hadn't added all args yet since I didn't need them yet myself, but sounds like you do. I will add more params soon.

**Comment by mxchinegod** [comment]
> Agreed, thanks for the feedback! I hadn't added all args yet since I didn't need them yet myself, but sounds like you do. I will add more params soon.

I'm working on a PR now which will not be perfect imo but will get us started I hope... can't test because of a CUDA mismatch situation in my enterprise environment but can submit and cross fingers

edit: [🙏](https://github.com/substratusai/vllm-docker/pull/4)

**Comment by samos123** [comment]
Fixed by #5
