### ISSUE TITLE
 Image tag v0.6.2 runs vllm v0.5.5

### ISSUE THREAD

**Issue by mpagnucco** [substratusai/vllm-docker#30]
Pulled docker image tag v0.6.2 and it runs vllm v0.5.5.
Looks like the Dockerfile is always building v0.5.5 hardcoded due to VERSION arg:

https://github.com/substratusai/vllm-docker/blob/1a597e653a065a5f99f774e85e0843b626a19ca7/Dockerfile#L1C1-L1C19

**Comment by samos123** [comment]
I think this may have happened when @nstogner published new CPU/ TPU images. I will update and and publish.

**Comment by samos123** [comment]
new images have been updated. I'm also in the process of publishing v0.6.3 for CPU, GPU and TPU.
